=== easyjax/cli/src/main/resources/xsd/cli.xsd
<!--
  Copyright Safris Software 2008
  
  This code is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<xs:schema
  elementFormDefault="qualified"
  targetNamespace="http://commons.safris.org/cli.xsd"
  xmlns:cli="http://commons.safris.org/cli.xsd"
  xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="arguments">
    <xs:complexType>
      <xs:sequence minOccurs="0" maxOccurs="unbounded">
        <xs:element name="option">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="name">
                <xs:complexType>
                	<xs:attribute name="long" type="cli:NCWName" use="required"/>
                	<xs:attribute name="short" type="cli:NCWName" use="required"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="argument" minOccurs="0">
                <xs:complexType>
                	<xs:attribute name="name" type="cli:NCWName" use="required"/>
                	<xs:attribute name="use" default="optional">
                		<xs:simpleType>
                			<xs:restriction base="xs:token">
                				<xs:enumeration value="required"/>
                				<xs:enumeration value="optional"/>
                			</xs:restriction>
                		</xs:simpleType>
                	</xs:attribute>
                	<xs:attribute name="default" type="xs:string"/>
                </xs:complexType>
              </xs:element>
              <xs:element name="description" type="xs:string"/>
            </xs:sequence>
            <xs:attribute name="required" type="xs:boolean" default="false"/>
            <xs:attribute name="valueSeparator" type="cli:char" default=" "/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>

    <xs:unique name="uniqueLongName">
      <xs:selector xpath="cli:option/cli:name"/>
      <xs:field xpath="@long"/>
    </xs:unique>

    <xs:unique name="uniqueShortName">
      <xs:selector xpath="cli:option/cli:name"/>
      <xs:field xpath="@short"/>
    </xs:unique>

  </xs:element>

  <xs:simpleType name="NCWName">
    <xs:restriction base="xs:NCName">
      <xs:pattern value="[\S]*"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="char">
    <xs:restriction base="xs:normalizedString">
      <xs:maxLength value="1"/>
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

</xs:schema>

=== easyjax/cli/src/test/resources/xml/cli.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
  Copyright Safris Software 2008
  
  This code is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.
  
  This program is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.
  
  You should have received a copy of the GNU General Public License
  along with this program.  If not, see <http://www.gnu.org/licenses/>.
-->

<arguments
  xmlns="http://commons.safris.org/cli.xsd"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://commons.safris.org/cli.xsd ../../../main/resources/xsd/cli.xsd">

  <option required="true" valueSeparator="=">
    <name long="date" short="D"/>
    <argument name="yyMMdd" use="optional"/>
    <description>use the yyMMdd date</description>
  </option>

  <option required="true">
    <name long="user" short="U"/>
    <argument name="USER" use="required" default="asgus"/>
    <description>run on the specified USER</description>
  </option>

  <option>
    <name long="silent"/>
    <description>silent mode</description>
  </option>

  <option>
    <name short="V"/>
    <description>verbose mode</description>
  </option>

</arguments>
